### ISSUE TITLE
[TODO] Support for Google Cloud Service Account authentication

### ISSUE THREAD

**Issue by skomma** [weseek/mongodb-awesome-backup#17]
https://cloud.google.com/storage/docs/authentication#gsutilauth

- [ ] Add `gcloud` command to Docker image
- [ ] Add execution `gcloud auth activate-service-account` to any script
- [ ] Add usage in README.md
- [ ] Add e2e test case

**Comment by ryu-sato** [comment]
This issue was resolved by PR #23, and released at mab [v0.5.7](https://github.com/weseek/mongodb-awesome-backup/releases/tag/v0.5.7)
